# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chris\OneDrive\Desktop\For Python Code\penpal\Con NPass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets

# Get the absolute path of the current directory (LogInPage.py)
current_directory = os.path.dirname(os.path.abspath(__file__))

# Build the general path to the resources/images folder
images_folder = os.path.join(current_directory, '..', 'resources', 'images')
Interest_assets_folder = os.path.join(current_directory, '..', 'resources', 'images', 'Interest_assets')


class Ui_CNP_Fullpage(object):
    def setupUi(self, CNP_Fullpage):
        CNP_Fullpage.setObjectName("CNP_Fullpage")
        CNP_Fullpage.resize(1440, 780)
        CNP_Fullpage.setMinimumSize(QtCore.QSize(581, 96))
        CNP_Fullpage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.CNP_Header = QtWidgets.QFrame(CNP_Fullpage)
        self.CNP_Header.setGeometry(QtCore.QRect(0, 0, 1440, 105))
        self.CNP_Header.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:0, \n"
"    stop:0 #EDC27E, \n"
"    stop:0.526 #EDC27E, \n"
"    stop:1 #DC586D\n"
");\n"
"\n"
"")
        self.CNP_Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CNP_Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CNP_Header.setObjectName("CNP_Header")
        self.CNP_HeaderIcon = QtWidgets.QLabel(self.CNP_Header)
        self.CNP_HeaderIcon.setGeometry(QtCore.QRect(-70, -20, 274, 146))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.CNP_HeaderIcon.setFont(font)
        self.CNP_HeaderIcon.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.CNP_HeaderIcon.setText("")
        self.CNP_HeaderIcon.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../../../Downloads/HeaderIcon.png"))
        self.CNP_HeaderIcon.setScaledContents(True)
        self.CNP_HeaderIcon.setObjectName("CNP_HeaderIcon")
        self.frame = QtWidgets.QFrame(CNP_Fullpage)
        self.frame.setGeometry(QtCore.QRect(261, 149, 901, 602))
        self.frame.setMinimumSize(QtCore.QSize(901, 602))
        self.frame.setStyleSheet("background-color: rgb(255, 240, 216);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.CNP_EnterPassText = QtWidgets.QLabel(self.frame)
        self.CNP_EnterPassText.setGeometry(QtCore.QRect(50, 220, 351, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CNP_EnterPassText.sizePolicy().hasHeightForWidth())
        self.CNP_EnterPassText.setSizePolicy(sizePolicy)
        self.CNP_EnterPassText.setMinimumSize(QtCore.QSize(351, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.CNP_EnterPassText.setFont(font)
        self.CNP_EnterPassText.setStyleSheet("color: rgb(122, 12, 12); font-size: 23px;\n"
"background: transparent;")
        self.CNP_EnterPassText.setObjectName("CNP_EnterPassText")
        self.CNP_EnterPassBox = QtWidgets.QFrame(self.frame)
        self.CNP_EnterPassBox.setGeometry(QtCore.QRect(100, 280, 323, 36))
        self.CNP_EnterPassBox.setMinimumSize(QtCore.QSize(323, 36))
        self.CNP_EnterPassBox.setStyleSheet("background-color: rgb(255, 240, 216);\n"
"border: 2px solid #E58D76;\n"
"background: transparent;")
        self.CNP_EnterPassBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CNP_EnterPassBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CNP_EnterPassBox.setObjectName("CNP_EnterPassBox")
        self.CNP_SubmitButton = QtWidgets.QFrame(self.frame)
        self.CNP_SubmitButton.setGeometry(QtCore.QRect(300, 460, 119, 36))
        self.CNP_SubmitButton.setMinimumSize(QtCore.QSize(119, 36))
        self.CNP_SubmitButton.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.CNP_SubmitButton.setStyleSheet("border-color: rgb(220, 97, 88);\n"
"border: 3px solid #DC6158;\n"
"border-radius: 5px;\n"
"")
        self.CNP_SubmitButton.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CNP_SubmitButton.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CNP_SubmitButton.setObjectName("CNP_SubmitButton")
        self.label_5 = QtWidgets.QLabel(self.CNP_SubmitButton)
        self.label_5.setGeometry(QtCore.QRect(28, -23, 350, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(350, 36))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777212))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(220, 97, 88); font-size: 23px;\n"
"background: transparent;\n"
"border: none")
        self.label_5.setObjectName("label_5")
        self.CNP_ForgotPassTEXT = QtWidgets.QLabel(self.frame)
        self.CNP_ForgotPassTEXT.setGeometry(QtCore.QRect(110, 116, 1090, 125))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.CNP_ForgotPassTEXT.sizePolicy().hasHeightForWidth())
        self.CNP_ForgotPassTEXT.setSizePolicy(sizePolicy)
        self.CNP_ForgotPassTEXT.setMinimumSize(QtCore.QSize(788, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(False)
        self.CNP_ForgotPassTEXT.setFont(font)
        self.CNP_ForgotPassTEXT.setStyleSheet("color:rgb(122, 12, 12);")
        self.CNP_ForgotPassTEXT.setObjectName("CNP_ForgotPassTEXT")
        self.CNP_Logo = QtWidgets.QLabel(self.frame)
        self.CNP_Logo.setGeometry(QtCore.QRect(-50, 0, 245, 127))
        self.CNP_Logo.setText("")
        self.CNP_Logo.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../PenpalFE/FPlogo.png"))
        self.CNP_Logo.setScaledContents(True)
        self.CNP_Logo.setObjectName("CNP_Logo")
        self.CNP_image1 = QtWidgets.QLabel(self.frame)
        self.CNP_image1.setGeometry(QtCore.QRect(140, 0, 1131, 602))
        self.CNP_image1.setMinimumSize(QtCore.QSize(421, 602))
        self.CNP_image1.setStyleSheet("background: transparent;")
        self.CNP_image1.setText("")
        self.CNP_image1.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../PenpalFE/FPimage1.png"))
        self.CNP_image1.setScaledContents(True)
        self.CNP_image1.setObjectName("CNP_image1")
        self.CNP_ConNewPassText = QtWidgets.QLabel(self.frame)
        self.CNP_ConNewPassText.setGeometry(QtCore.QRect(50, 320, 351, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CNP_ConNewPassText.sizePolicy().hasHeightForWidth())
        self.CNP_ConNewPassText.setSizePolicy(sizePolicy)
        self.CNP_ConNewPassText.setMinimumSize(QtCore.QSize(351, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.CNP_ConNewPassText.setFont(font)
        self.CNP_ConNewPassText.setStyleSheet("color: rgb(122, 12, 12); font-size: 23px;\n"
"background: transparent;")
        self.CNP_ConNewPassText.setObjectName("CNP_ConNewPassText")
        self.CNP_ConNewPassBox = QtWidgets.QFrame(self.frame)
        self.CNP_ConNewPassBox.setGeometry(QtCore.QRect(100, 380, 323, 36))
        self.CNP_ConNewPassBox.setMinimumSize(QtCore.QSize(323, 36))
        self.CNP_ConNewPassBox.setStyleSheet("background-color: rgb(255, 240, 216);\n"
"border: 2px solid #E58D76;\n"
"background: transparent;")
        self.CNP_ConNewPassBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CNP_ConNewPassBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CNP_ConNewPassBox.setObjectName("CNP_ConNewPassBox")
        self.CNP_Shadow = QtWidgets.QLabel(self.frame)
        self.CNP_Shadow.setGeometry(QtCore.QRect(-30, 0, 1031, 601))
        self.CNP_Shadow.setStyleSheet("background: transparent;")
        self.CNP_Shadow.setText("")
        self.CNP_Shadow.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../PenpalFE/FPshadow.png"))
        self.CNP_Shadow.setScaledContents(True)
        self.CNP_Shadow.setObjectName("CNP_Shadow")

        self.retranslateUi(CNP_Fullpage)
        QtCore.QMetaObject.connectSlotsByName(CNP_Fullpage)

    def retranslateUi(self, CNP_Fullpage):
        _translate = QtCore.QCoreApplication.translate
        CNP_Fullpage.setWindowTitle(_translate("CNP_Fullpage", "Dialog"))
        self.CNP_EnterPassText.setText(_translate("CNP_Fullpage", "ENTER YOUR NEW PASSWORD:"))
        self.label_5.setText(_translate("CNP_Fullpage", "SUBMIT"))
        self.CNP_ForgotPassTEXT.setText(_translate("CNP_Fullpage", "FORGOT PASSWORD"))
        self.CNP_ConNewPassText.setText(_translate("CNP_Fullpage", "CONFIRM YOUR NEW PASSWORD:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CNP_Fullpage = QtWidgets.QDialog()
    ui = Ui_CNP_Fullpage()
    ui.setupUi(CNP_Fullpage)
    CNP_Fullpage.show()
    sys.exit(app.exec_())
