# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chris\OneDrive\Desktop\For Python Code\penpal\FRIENDS.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 1080)
        Dialog.setStyleSheet("COLOR:#FFFFFF;\n"
"")
        self.CUHeader = QtWidgets.QFrame(Dialog)
        self.CUHeader.setGeometry(QtCore.QRect(0, 0, 1440, 105))
        self.CUHeader.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:0, \n"
"    stop:0 #EDC27E, \n"
"    stop:0.526 #EDC27E, \n"
"    stop:1 #DC586D\n"
");\n"
"\n"
"")
        self.CUHeader.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.CUHeader.setFrameShadow(QtWidgets.QFrame.Raised)
        self.CUHeader.setObjectName("CUHeader")
        self.HeaderIcon = QtWidgets.QLabel(self.CUHeader)
        self.HeaderIcon.setGeometry(QtCore.QRect(-70, -20, 274, 146))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.HeaderIcon.setFont(font)
        self.HeaderIcon.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.HeaderIcon.setText("")
        self.HeaderIcon.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\HeaderIcon.png"))
        self.HeaderIcon.setScaledContents(True)
        self.HeaderIcon.setObjectName("HeaderIcon")
        self.FRIENDS = QtWidgets.QLabel(Dialog)
        self.FRIENDS.setGeometry(QtCore.QRect(110, 290, 1291, 661))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.FRIENDS.setFont(font)
        self.FRIENDS.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.FRIENDS.setText("")
        self.FRIENDS.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\FRIENDS.png"))
        self.FRIENDS.setScaledContents(True)
        self.FRIENDS.setObjectName("FRIENDS")
        self.FRIENDS_2 = QtWidgets.QLabel(Dialog)
        self.FRIENDS_2.setGeometry(QtCore.QRect(240, 60, 971, 441))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.FRIENDS_2.setFont(font)
        self.FRIENDS_2.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.FRIENDS_2.setText("")
        self.FRIENDS_2.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\FRIENDS1.png"))
        self.FRIENDS_2.setScaledContents(True)
        self.FRIENDS_2.setObjectName("FRIENDS_2")
        self.CONT = QtWidgets.QPushButton(Dialog)
        self.CONT.setGeometry(QtCore.QRect(690, 960, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CONT.setFont(font)
        self.CONT.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.CONT.setStyleSheet("font:30px;\n"
"background-color: rgb(255, 203, 158);\n"
"border: 2px solid #FFFFFF;\n"
"Color:#BE7928;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.CONT.setObjectName("CONT")
        self.FRIENDS.raise_()
        self.CUHeader.raise_()
        self.FRIENDS_2.raise_()
        self.CONT.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CONT.setText(_translate("Dialog", "CONTINUE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
