# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\PENPAL\FriendMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os

# Get the absolute path of the current directory
current_directory = os.path.dirname(os.path.abspath(__file__))

# Build the general path to the resources/images folder
images_folder = os.path.join(current_directory, '..', 'resources', 'images')


class Ui_FriendMenu(object):
    def setupUi(self, FriendMenu):
        FriendMenu.setObjectName("FriendMenu")
        FriendMenu.resize(1440, 780)
        FriendMenu.setStyleSheet("background-color: rgb(255, 249, 240);")
        
#Header
        self.FM_Header = QtWidgets.QFrame(FriendMenu)
        self.FM_Header.setGeometry(QtCore.QRect(0, 0, 1440, 105))
        self.FM_Header.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:0, \n"
"    stop:0 #EDC27E, \n"
"    stop:0.526 #EDC27E, \n"
"    stop:1 #DC586D\n"
");\n"
"\n"
"")
        self.FM_Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FM_Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FM_Header.setObjectName("FM_Header")
        
#Header Icon
        self.FM_HeaderIcon = QtWidgets.QLabel(self.FM_Header)
        self.FM_HeaderIcon.setGeometry(QtCore.QRect(-50, -30, 242, 159))
        self.FM_HeaderIcon.setStyleSheet("background:transparent;\n"
"")
        self.FM_HeaderIcon.setText("")
        self.FM_HeaderIcon.setPixmap(QtGui.QPixmap(os.path.join(images_folder , "HeaderIcon.png")))
        self.FM_HeaderIcon.setScaledContents(True)
        self.FM_HeaderIcon.setObjectName("FM_HeaderIcon")
        
#Friend Request Frame
        self.FM_FriendRequestFrame = QtWidgets.QFrame(FriendMenu)
        self.FM_FriendRequestFrame.setGeometry(QtCore.QRect(140, 140, 711, 600))
        self.FM_FriendRequestFrame.setStyleSheet("\n"
"border-radius: 5px;\n"
"border: 3px solid #BE7928;\n"
"background-color: rgb(255, 214, 182);")
        self.FM_FriendRequestFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FM_FriendRequestFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FM_FriendRequestFrame.setObjectName("FM_FriendRequestFrame")
        
#Friend's List Frame
        self.FM_FriendListFrame = QtWidgets.QFrame(FriendMenu)
        self.FM_FriendListFrame.setGeometry(QtCore.QRect(880, 140, 445, 600))
        self.FM_FriendListFrame.setStyleSheet("background-color: rgb(255, 240, 216);\n"
"border-radius: 5px;\n"
"border: 3px solid #BE7928;\n"
"")
        self.FM_FriendListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.FM_FriendListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.FM_FriendListFrame.setObjectName("FM_FriendListFrame")
        
#Home Push Button
        self.FM_HomePB = QtWidgets.QPushButton(FriendMenu)
        self.FM_HomePB.setGeometry(QtCore.QRect(950, 50, 150, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_HomePB.setFont(font)
        self.FM_HomePB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_HomePB.setStyleSheet("color:rgb(255, 255, 255);\n"
"border-color: rgb(229, 141, 118);\n"
"border: 3px solid #FFFFFF;\n"
"border-radius: 20px;\n"
"background: transparent;\n"
"")
        self.FM_HomePB.setObjectName("FM_HomePB")
        
#Profile Push Button
        self.FM_ProfilePB = QtWidgets.QPushButton(FriendMenu)
        self.FM_ProfilePB.setGeometry(QtCore.QRect(1110, 50, 150, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_ProfilePB.setFont(font)
        self.FM_ProfilePB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_ProfilePB.setStyleSheet("color:rgb(255, 255, 255);\n"
"border-color: rgb(229, 141, 118);\n"
"border: 3px solid #FFFFFF;\n"
"border-radius: 20px;\n"
"background: transparent;\n"
"")
        self.FM_ProfilePB.setObjectName("FM_ProfilePB")

#Log Out Push Button
        self.FM_LogOutPB = QtWidgets.QPushButton(FriendMenu)
        self.FM_LogOutPB.setGeometry(QtCore.QRect(1270, 50, 150, 45))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_LogOutPB.setFont(font)
        self.FM_LogOutPB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_LogOutPB.setStyleSheet("color:rgb(255, 255, 255);\n"
"border-color: rgb(229, 141, 118);\n"
"border: 3px solid #FFFFFF;\n"
"border-radius: 20px;\n"
"background: transparent;\n"
"")
        self.FM_LogOutPB.setObjectName("FM_LogOutPB")
        
#Friend Request Label
        self.FM_FriendRequestsLBL = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequestsLBL.setGeometry(QtCore.QRect(170, 160, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequestsLBL.setFont(font)
        self.FM_FriendRequestsLBL.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequestsLBL.setObjectName("FM_FriendRequestsLBL")
        
#Friend Request 1
        self.FM_FriendRequest1 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest1.setGeometry(QtCore.QRect(250, 220, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest1.setFont(font)
        self.FM_FriendRequest1.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest1.setObjectName("FM_FriendRequest1")
        
#Friend Request 2
        self.FM_FriendRequest2 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest2.setGeometry(QtCore.QRect(250, 270, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest2.setFont(font)
        self.FM_FriendRequest2.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest2.setObjectName("FM_FriendRequest2")
        
#Friend Request 3
        self.FM_FriendRequest3 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest3.setGeometry(QtCore.QRect(250, 320, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest3.setFont(font)
        self.FM_FriendRequest3.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest3.setObjectName("FM_FriendRequest3")
        
#Friend Request 4
        self.FM_FriendRequest4 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest4.setGeometry(QtCore.QRect(250, 370, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest4.setFont(font)
        self.FM_FriendRequest4.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest4.setObjectName("FM_FriendRequest4")
        
#Friend Request 5
        self.FM_FriendRequest5 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest5.setGeometry(QtCore.QRect(250, 420, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest5.setFont(font)
        self.FM_FriendRequest5.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest5.setObjectName("FM_FriendRequest5")
        
#Friend Request 6
        self.FM_FriendRequest6 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest6.setGeometry(QtCore.QRect(250, 470, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest6.setFont(font)
        self.FM_FriendRequest6.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest6.setObjectName("FM_FriendRequest6")
        
#Friend Request 7
        self.FM_FriendRequest7 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest7.setGeometry(QtCore.QRect(250, 520, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest7.setFont(font)
        self.FM_FriendRequest7.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest7.setObjectName("FM_FriendRequest7")
        
#Friend Request 8
        self.FM_FriendRequest8 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest8.setGeometry(QtCore.QRect(250, 570, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest8.setFont(font)
        self.FM_FriendRequest8.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest8.setObjectName("FM_FriendRequest8")

#Friend Request 9
        self.FM_FriendRequest9 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest9.setGeometry(QtCore.QRect(250, 620, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest9.setFont(font)
        self.FM_FriendRequest9.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest9.setObjectName("FM_FriendRequest9")
        
#Friend Request 10
        self.FM_FriendRequest10 = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendRequest10.setGeometry(QtCore.QRect(250, 670, 500, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendRequest10.setFont(font)
        self.FM_FriendRequest10.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendRequest10.setObjectName("FM_FriendRequest10")
        
#Decline Push Button 1
        self.FM_Decline1PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline1PB.setGeometry(QtCore.QRect(710, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline1PB.setFont(font)
        self.FM_Decline1PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline1PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline1PB.setObjectName("FM_Decline1PB")
        
#Accept Push Button 2
        self.FM_Accept2PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept2PB.setGeometry(QtCore.QRect(610, 280, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept2PB.setFont(font)
        self.FM_Accept2PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept2PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept2PB.setObjectName("FM_Accept2PB")
        
#Decline Push Button 2
        self.FM_Decline2PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline2PB.setGeometry(QtCore.QRect(710, 280, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline2PB.setFont(font)
        self.FM_Decline2PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline2PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline2PB.setObjectName("FM_Decline2PB")
        
#Accept Push Button 1
        self.FM_Accept1PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept1PB.setGeometry(QtCore.QRect(610, 230, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept1PB.setFont(font)
        self.FM_Accept1PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept1PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"")
        self.FM_Accept1PB.setObjectName("FM_Accept1PB")
        
#Accept Push Button 3
        self.FM_Accept3PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept3PB.setGeometry(QtCore.QRect(610, 330, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept3PB.setFont(font)
        self.FM_Accept3PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept3PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept3PB.setObjectName("FM_Accept3PB")
        
#Accept Push Button 4
        self.FM_Accept4PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept4PB.setGeometry(QtCore.QRect(610, 380, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept4PB.setFont(font)
        self.FM_Accept4PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept4PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept4PB.setObjectName("FM_Accept4PB")
        
#Accept Push Button 5
        self.FM_Accept5PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept5PB.setGeometry(QtCore.QRect(610, 430, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept5PB.setFont(font)
        self.FM_Accept5PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept5PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept5PB.setObjectName("FM_Accept5PB")
        
#Accept Push Button 6
        self.FM_Accept6PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept6PB.setGeometry(QtCore.QRect(610, 480, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept6PB.setFont(font)
        self.FM_Accept6PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept6PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept6PB.setObjectName("FM_Accept6PB")
        
#Accept Push Button 7
        self.FM_Accept7PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept7PB.setGeometry(QtCore.QRect(610, 530, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept7PB.setFont(font)
        self.FM_Accept7PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept7PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept7PB.setObjectName("FM_Accept7PB")
        
#Accept Push Button 8
        self.FM_Accept8PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept8PB.setGeometry(QtCore.QRect(610, 580, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept8PB.setFont(font)
        self.FM_Accept8PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept8PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept8PB.setObjectName("FM_Accept8PB")
        
#Accept Push Button 9
        self.FM_Accept9PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept9PB.setGeometry(QtCore.QRect(610, 630, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept9PB.setFont(font)
        self.FM_Accept9PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept9PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept9PB.setObjectName("FM_Accept9PB")
        
#Accept Push Button 10
        self.FM_Accept10PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Accept10PB.setGeometry(QtCore.QRect(610, 680, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Accept10PB.setFont(font)
        self.FM_Accept10PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Accept10PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"\n"
"")
        self.FM_Accept10PB.setObjectName("FM_Accept10PB")
        
#Decline Push Button 3
        self.FM_Decline3PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline3PB.setGeometry(QtCore.QRect(710, 330, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline3PB.setFont(font)
        self.FM_Decline3PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline3PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline3PB.setObjectName("FM_Decline3PB")
        
#Decline Push Button 4
        self.FM_Decline4PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline4PB.setGeometry(QtCore.QRect(710, 380, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline4PB.setFont(font)
        self.FM_Decline4PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline4PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline4PB.setObjectName("FM_Decline4PB")
        
#Decline Push Button 5
        self.FM_Decline5PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline5PB.setGeometry(QtCore.QRect(710, 430, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline5PB.setFont(font)
        self.FM_Decline5PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline5PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline5PB.setObjectName("FM_Decline5PB")
        
#Decline Push Button 6
        self.FM_Decline6PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline6PB.setGeometry(QtCore.QRect(710, 480, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline6PB.setFont(font)
        self.FM_Decline6PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline6PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline6PB.setObjectName("FM_Decline6PB")
        
#Decline Push Button 7
        self.FM_Decline7PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline7PB.setGeometry(QtCore.QRect(710, 530, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline7PB.setFont(font)
        self.FM_Decline7PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline7PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline7PB.setObjectName("FM_Decline7PB")
        
#Decline Push Button 8
        self.FM_Decline8PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline8PB.setGeometry(QtCore.QRect(710, 580, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline8PB.setFont(font)
        self.FM_Decline8PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline8PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline8PB.setObjectName("FM_Decline8PB")
        
#Decline Push Button 9
        self.FM_Decline9PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline9PB.setGeometry(QtCore.QRect(710, 630, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline9PB.setFont(font)
        self.FM_Decline9PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline9PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline9PB.setObjectName("FM_Decline9PB")
        
#Decline Push Button 10
        self.FM_Decline10PB = QtWidgets.QPushButton(FriendMenu)
        self.FM_Decline10PB.setGeometry(QtCore.QRect(710, 680, 93, 28))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setBold(True)
        font.setWeight(75)
        self.FM_Decline10PB.setFont(font)
        self.FM_Decline10PB.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_Decline10PB.setStyleSheet("background-color: rgb(255, 187, 173);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.FM_Decline10PB.setObjectName("FM_Decline10PB")
        
#Friend's List Label (IList of Friends)
        self.FM_FriendList = QtWidgets.QLabel(FriendMenu)
        self.FM_FriendList.setGeometry(QtCore.QRect(1000, 150, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_FriendList.setFont(font)
        self.FM_FriendList.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_FriendList.setObjectName("FM_FriendList")
        
#Accepted Friend 1
        self.FM_AcceptedFriend1 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend1.setGeometry(QtCore.QRect(990, 220, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend1.setFont(font)
        self.FM_AcceptedFriend1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend1.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend1.setObjectName("FM_AcceptedFriend1")
        
#Accepted Friend 2
        self.FM_AcceptedFriend2 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend2.setGeometry(QtCore.QRect(990, 260, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend2.setFont(font)
        self.FM_AcceptedFriend2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend2.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend2.setObjectName("FM_AcceptedFriend2")
        
#Accepted Friend 3
        self.FM_AcceptedFriend3 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend3.setGeometry(QtCore.QRect(990, 300, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend3.setFont(font)
        self.FM_AcceptedFriend3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend3.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend3.setObjectName("FM_AcceptedFriend3")
        
#Accepted Friend 4
        self.FM_AcceptedFriend4 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend4.setGeometry(QtCore.QRect(990, 340, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend4.setFont(font)
        self.FM_AcceptedFriend4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend4.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend4.setObjectName("FM_AcceptedFriend4")
        
#Accepted Friend 5
        self.FM_AcceptedFriend5 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend5.setGeometry(QtCore.QRect(990, 380, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend5.setFont(font)
        self.FM_AcceptedFriend5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend5.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend5.setObjectName("FM_AcceptedFriend5")

#Accepted Friend 6
        self.FM_AcceptedFriend6 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend6.setGeometry(QtCore.QRect(990, 420, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend6.setFont(font)
        self.FM_AcceptedFriend6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend6.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend6.setObjectName("FM_AcceptedFriend6")
        
#Accepted Friend 7
        self.FM_AcceptedFriend7 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend7.setGeometry(QtCore.QRect(990, 460, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend7.setFont(font)
        self.FM_AcceptedFriend7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend7.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend7.setObjectName("FM_AcceptedFriend7")
        
#Accepted Friend 8
        self.FM_AcceptedFriend8 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend8.setGeometry(QtCore.QRect(990, 500, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend8.setFont(font)
        self.FM_AcceptedFriend8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend8.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend8.setObjectName("FM_AcceptedFriend8")
        
#Accepted Friend 9
        self.FM_AcceptedFriend9 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend9.setGeometry(QtCore.QRect(990, 540, 251, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend9.setFont(font)
        self.FM_AcceptedFriend9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend9.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend9.setObjectName("FM_AcceptedFriend9")
        
#Accepted Friend 10
        self.FM_AcceptedFriend10 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend10.setGeometry(QtCore.QRect(990, 580, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend10.setFont(font)
        self.FM_AcceptedFriend10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend10.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend10.setObjectName("FM_AcceptedFriend10")
        
#Accepted Friend 11
        self.FM_AcceptedFriend11 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend11.setGeometry(QtCore.QRect(990, 620, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend11.setFont(font)
        self.FM_AcceptedFriend11.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend11.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend11.setObjectName("FM_AcceptedFriend11")
        
#Accepted Friend 12
        self.FM_AcceptedFriend12 = QtWidgets.QLabel(FriendMenu)
        self.FM_AcceptedFriend12.setGeometry(QtCore.QRect(990, 660, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.FM_AcceptedFriend12.setFont(font)
        self.FM_AcceptedFriend12.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.FM_AcceptedFriend12.setStyleSheet("Background: transparent;\n"
"color: rgb(122, 12, 12);")
        self.FM_AcceptedFriend12.setObjectName("FM_AcceptedFriend12")

        self.retranslateUi(FriendMenu)
        QtCore.QMetaObject.connectSlotsByName(FriendMenu)

        self.FM_Accept1PB.setVisible(False)
        self.FM_Accept2PB.setVisible(False)
        self.FM_Accept3PB.setVisible(False)
        self.FM_Accept4PB.setVisible(False)
        self.FM_Accept5PB.setVisible(False)
        self.FM_Accept6PB.setVisible(False)
        self.FM_Accept7PB.setVisible(False)
        self.FM_Accept8PB.setVisible(False)
        self.FM_Accept9PB.setVisible(False)
        self.FM_Accept10PB.setVisible(False)

        self.FM_Decline1PB.setVisible(False)
        self.FM_Decline2PB.setVisible(False)
        self.FM_Decline3PB.setVisible(False)
        self.FM_Decline4PB.setVisible(False)
        self.FM_Decline5PB.setVisible(False)
        self.FM_Decline6PB.setVisible(False)
        self.FM_Decline7PB.setVisible(False)
        self.FM_Decline8PB.setVisible(False)
        self.FM_Decline9PB.setVisible(False)
        self.FM_Decline10PB.setVisible(False)

    def retranslateUi(self, FriendMenu):
        _translate = QtCore.QCoreApplication.translate
        FriendMenu.setWindowTitle(_translate("FriendMenu", "Dialog"))
        self.FM_HomePB.setText(_translate("FriendMenu", "Home"))
        self.FM_ProfilePB.setText(_translate("FriendMenu", "Profile"))
        self.FM_LogOutPB.setText(_translate("FriendMenu", "Log Out"))
        self.FM_FriendRequestsLBL.setText(_translate("FriendMenu", "Friend Requests:"))
        self.FM_FriendRequest1.setText(_translate("FriendMenu", "Friend Request1"))
        self.FM_FriendRequest2.setText(_translate("FriendMenu", "Friend Request2"))
        self.FM_FriendRequest3.setText(_translate("FriendMenu", "Friend Request3"))
        self.FM_FriendRequest4.setText(_translate("FriendMenu", "Friend Request4"))
        self.FM_FriendRequest5.setText(_translate("FriendMenu", "Friend Request5"))
        self.FM_FriendRequest6.setText(_translate("FriendMenu", "Friend Request6"))
        self.FM_FriendRequest7.setText(_translate("FriendMenu", "Friend Request7"))
        self.FM_FriendRequest8.setText(_translate("FriendMenu", "Friend Request8"))
        self.FM_FriendRequest9.setText(_translate("FriendMenu", "Friend Request9"))
        self.FM_FriendRequest10.setText(_translate("FriendMenu", "Friend Request10"))
        self.FM_Decline1PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Accept2PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Decline2PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Accept1PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept3PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept4PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept5PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept6PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept7PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept8PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept9PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Accept10PB.setText(_translate("FriendMenu", "Accept"))
        self.FM_Decline3PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline4PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline5PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline6PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline7PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline8PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline9PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_Decline10PB.setText(_translate("FriendMenu", "Decline"))
        self.FM_FriendList.setText(_translate("FriendMenu", "List of Friends"))
        self.FM_AcceptedFriend1.setText(_translate("FriendMenu", "Accepted Friend 1"))
        self.FM_AcceptedFriend2.setText(_translate("FriendMenu", "Accepted Friend 2"))
        self.FM_AcceptedFriend3.setText(_translate("FriendMenu", "Accepted Friend 3"))
        self.FM_AcceptedFriend4.setText(_translate("FriendMenu", "Accepted Friend 4"))
        self.FM_AcceptedFriend5.setText(_translate("FriendMenu", "Accepted Friend 5"))
        self.FM_AcceptedFriend6.setText(_translate("FriendMenu", "Accepted Friend 6"))
        self.FM_AcceptedFriend7.setText(_translate("FriendMenu", "Accepted Friend 7"))
        self.FM_AcceptedFriend8.setText(_translate("FriendMenu", "Accepted Friend 8"))
        self.FM_AcceptedFriend9.setText(_translate("FriendMenu", "Accepted Friend 9"))
        self.FM_AcceptedFriend10.setText(_translate("FriendMenu", "Accepted Friend 10"))
        self.FM_AcceptedFriend11.setText(_translate("FriendMenu", "Accepted Friend 11"))
        self.FM_AcceptedFriend12.setText(_translate("FriendMenu", "Accepted Friend 12"))


if __name__ == "__main__":
        import sys
        app = QtWidgets.QApplication(sys.argv)
        FriendMenu = QtWidgets.QDialog()
        ui = Ui_FriendMenu()
        ui.setupUi(FriendMenu)
        FriendMenu.show()
        sys.exit(app.exec_())
