# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chris\OneDrive\Desktop\For Python Code\penpal\OTP.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os
from PyQt5 import QtCore, QtGui, QtWidgets

# Get the absolute path of the current directory (LogInPage.py)
current_directory = os.path.dirname(os.path.abspath(__file__))

# Build the general path to the resources/images folder
images_folder = os.path.join(current_directory, '..', 'resources', 'images')
Forget_Pass_assests_folder = os.path.join(current_directory, '..', 'resources', 'images', 'Forget_Pass_assests')

class Ui_OTP_Fullpage(object):
    def setupUi(self, OTP_Fullpage):
        OTP_Fullpage.setObjectName("OTP_Fullpage")
        OTP_Fullpage.resize(1440, 780)
        OTP_Fullpage.setMinimumSize(QtCore.QSize(581, 96))
        OTP_Fullpage.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.OTP_Top = QtWidgets.QFrame(OTP_Fullpage)
        self.OTP_Top.setGeometry(QtCore.QRect(0, 0, 1440, 105))
        self.OTP_Top.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:0, \n"
"    stop:0 #EDC27E, \n"
"    stop:0.526 #EDC27E, \n"
"    stop:1 #DC586D\n"
");\n"
"\n"
"")
        self.OTP_Top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OTP_Top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OTP_Top.setObjectName("OTP_Top")
        self.OTP_HeaderIcon = QtWidgets.QLabel(self.OTP_Top)
        self.OTP_HeaderIcon.setGeometry(QtCore.QRect(-70, -20, 274, 146))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.OTP_HeaderIcon.setFont(font)
        self.OTP_HeaderIcon.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.OTP_HeaderIcon.setText("")
        self.OTP_HeaderIcon.setPixmap(QtGui.QPixmap(os.path.join(images_folder, 'HeaderIcon.png')))
        self.OTP_HeaderIcon.setScaledContents(True)
        self.OTP_HeaderIcon.setObjectName("OTP_HeaderIcon")
        self.frame = QtWidgets.QFrame(OTP_Fullpage)
        self.frame.setGeometry(QtCore.QRect(261, 149, 901, 602))
        self.frame.setMinimumSize(QtCore.QSize(901, 602))
        self.frame.setStyleSheet("background-color: rgb(255, 240, 216);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.OTP_Word = QtWidgets.QLabel(self.frame)
        self.OTP_Word.setGeometry(QtCore.QRect(60, 240, 351, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OTP_Word.sizePolicy().hasHeightForWidth())
        self.OTP_Word.setSizePolicy(sizePolicy)
        self.OTP_Word.setMinimumSize(QtCore.QSize(351, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.OTP_Word.setFont(font)
        self.OTP_Word.setStyleSheet("color: rgb(122, 12, 12); font-size: 23px;")
        self.OTP_Word.setObjectName("OTP_Word")
        self.OTP_Box = QtWidgets.QFrame(self.frame)
        self.OTP_Box.setGeometry(QtCore.QRect(100, 290, 323, 36))
        self.OTP_Box.setMinimumSize(QtCore.QSize(323, 36))
        self.OTP_Box.setStyleSheet("background-color: rgb(255, 240, 216);\n"
"border: 2px solid #E58D76;")
        self.OTP_Box.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.OTP_Box.setFrameShadow(QtWidgets.QFrame.Raised)
        self.OTP_Box.setObjectName("OTP_Box")
        self.frame_3 = QtWidgets.QFrame(self.frame)
        self.frame_3.setGeometry(QtCore.QRect(300, 410, 119, 36))
        self.frame_3.setMinimumSize(QtCore.QSize(119, 36))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setStyleSheet("border-color: rgb(220, 97, 88);\n"
"border: 3px solid #DC6158;\n"
"border-radius: 5px;\n"
"")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_5 = QtWidgets.QLabel(self.frame_3)
        self.label_5.setGeometry(QtCore.QRect(28, -23, 350, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMinimumSize(QtCore.QSize(350, 36))
        self.label_5.setMaximumSize(QtCore.QSize(16777215, 16777212))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(220, 97, 88); font-size: 23px;\n"
"background: transparent;\n"
"border: none")
        self.label_5.setObjectName("label_5")
        self.ForgotPassTEXT = QtWidgets.QLabel(self.frame)
        self.ForgotPassTEXT.setGeometry(QtCore.QRect(90, 135, 800, 152))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.ForgotPassTEXT.sizePolicy().hasHeightForWidth())
        self.ForgotPassTEXT.setSizePolicy(sizePolicy)
        self.ForgotPassTEXT.setMinimumSize(QtCore.QSize(488, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(16)
        font.setBold(False)
        self.ForgotPassTEXT.setFont(font)
        self.ForgotPassTEXT.setStyleSheet("color:rgb(122, 12, 12);")
        self.ForgotPassTEXT.setObjectName("ForgotPassTEXT")
        self.OTP_Shadow = QtWidgets.QLabel(self.frame)
        self.OTP_Shadow.setGeometry(QtCore.QRect(0, 0, 1031, 601))
        self.OTP_Shadow.setStyleSheet("background: transparent;")
        self.OTP_Shadow.setText("")
        self.OTP_Shadow.setPixmap(QtGui.QPixmap(os.path.join(Forget_Pass_assests_folder, 'FPshadow.png')))
        self.OTP_Shadow.setScaledContents(True)
        self.OTP_Shadow.setObjectName("OTP_Shadow")
        self.OTP_Logo = QtWidgets.QLabel(self.frame)
        self.OTP_Logo.setGeometry(QtCore.QRect(-50, 0, 245, 127))
        self.OTP_Logo.setText("")
        self.OTP_Logo.setPixmap(QtGui.QPixmap(os.path.join(Forget_Pass_assests_folder, 'FPlogo.png')))
        self.OTP_Logo.setScaledContents(True)
        self.OTP_Logo.setObjectName("OTP_Logo")
        self.OTP_TextWord = QtWidgets.QLabel(self.frame)
        self.OTP_TextWord.setGeometry(QtCore.QRect(150, 330, 351, 51))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.OTP_TextWord.sizePolicy().hasHeightForWidth())
        self.OTP_TextWord.setSizePolicy(sizePolicy)
        self.OTP_TextWord.setMinimumSize(QtCore.QSize(351, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.OTP_TextWord.setFont(font)
        self.OTP_TextWord.setStyleSheet("color: rgb(122, 12, 12); font-size: 18px;\n"
"background: transparent;\n"
"")
        self.OTP_TextWord.setObjectName("OTP_TextWord")
        self.frame_4 = QtWidgets.QFrame(self.frame)
        self.frame_4.setGeometry(QtCore.QRect(70, 410, 119, 36))
        self.frame_4.setMinimumSize(QtCore.QSize(119, 36))
        self.frame_4.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.frame_4.setStyleSheet("border-color: rgb(220, 97, 88);\n"
"border: 3px solid #DC6158;\n"
"border-radius: 5px;\n"
"")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(30, -22, 350, 81))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(350, 36))
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777212))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(220, 97, 88); font-size: 23px;\n"
"background: transparent;\n"
"border: none")
        self.label_6.setObjectName("label_6")
        self.FPimage1 = QtWidgets.QLabel(self.frame)
        self.FPimage1.setGeometry(QtCore.QRect(170, 0, 1131, 602))
        self.FPimage1.setMinimumSize(QtCore.QSize(421, 602))
        self.FPimage1.setStyleSheet("background: transparent;")
        self.FPimage1.setText("")
        self.FPimage1.setPixmap(QtGui.QPixmap(os.path.join(images_folder, 'BGimage13.png')))
        self.FPimage1.setScaledContents(True)
        self.FPimage1.setObjectName("FPimage1")

        self.retranslateUi(OTP_Fullpage)
        QtCore.QMetaObject.connectSlotsByName(OTP_Fullpage)

    def retranslateUi(self, OTP_Fullpage):
        _translate = QtCore.QCoreApplication.translate
        OTP_Fullpage.setWindowTitle(_translate("OTP_Fullpage", "Dialog"))
        self.OTP_Word.setText(_translate("OTP_Fullpage", "OTP:"))
        self.label_5.setText(_translate("OTP_Fullpage", "SUBMIT"))
        self.ForgotPassTEXT.setText(_translate("OTP_Fullpage", "FORGOT PASSWORD"))
        self.OTP_TextWord.setText(_translate("OTP_Fullpage", "Please check your email address for the  Required OTP to verify your account."))
        self.label_6.setText(_translate("OTP_Fullpage", "RESEND"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OTP_Fullpage = QtWidgets.QDialog()
    ui = Ui_OTP_Fullpage()
    ui.setupUi(OTP_Fullpage)
    OTP_Fullpage.show()
    sys.exit(app.exec_())
