# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chris\OneDrive\Desktop\For Python Code\penpal\AboutUPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 3975)
        Dialog.setStyleSheet("\n"
"background-color: rgb(255, 255, 255);")
        self.AU_header = QtWidgets.QFrame(Dialog)
        self.AU_header.setGeometry(QtCore.QRect(0, 0, 1440, 105))
        self.AU_header.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:0, \n"
"    stop:0 #EDC27E, \n"
"    stop:0.526 #EDC27E, \n"
"    stop:1 #DC586D\n"
");\n"
"\n"
"")
        self.AU_header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AU_header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AU_header.setObjectName("AU_header")
        self.HeaderIcon = QtWidgets.QLabel(self.AU_header)
        self.HeaderIcon.setGeometry(QtCore.QRect(-70, -20, 274, 146))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.HeaderIcon.setFont(font)
        self.HeaderIcon.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.HeaderIcon.setText("")
        self.HeaderIcon.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\HeaderIcon.png"))
        self.HeaderIcon.setScaledContents(True)
        self.HeaderIcon.setObjectName("HeaderIcon")
        self.LogIn_2 = QtWidgets.QPushButton(self.AU_header)
        self.LogIn_2.setGeometry(QtCore.QRect(1130, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.LogIn_2.setFont(font)
        self.LogIn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.LogIn_2.setStyleSheet("font:30px;\n"
"color: #FFFFFF;\n"
"border: 2px solid #FFFFFF;\n"
"background: transparent;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.LogIn_2.setObjectName("LogIn_2")
        self.SignUp = QtWidgets.QPushButton(self.AU_header)
        self.SignUp.setGeometry(QtCore.QRect(1250, 60, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.SignUp.setFont(font)
        self.SignUp.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.SignUp.setStyleSheet("font:30px;\n"
"color: #FFFFFF;\n"
"border: 2px solid #FFFFFF;\n"
"background: transparent;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.SignUp.setObjectName("SignUp")
        self.AUimage1 = QtWidgets.QLabel(Dialog)
        self.AUimage1.setGeometry(QtCore.QRect(-60, 70, 1561, 847))
        self.AUimage1.setStyleSheet("background: transparent;")
        self.AUimage1.setText("")
        self.AUimage1.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUimage1.png"))
        self.AUimage1.setScaledContents(True)
        self.AUimage1.setObjectName("AUimage1")
        self.HPbG = QtWidgets.QLabel(Dialog)
        self.HPbG.setGeometry(QtCore.QRect(-110, 1150, 1651, 491))
        self.HPbG.setStyleSheet("background: transparent;\n"
"")
        self.HPbG.setText("")
        self.HPbG.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\HPbG.png"))
        self.HPbG.setScaledContents(True)
        self.HPbG.setObjectName("HPbG")
        self.HPlshadow3 = QtWidgets.QLabel(Dialog)
        self.HPlshadow3.setGeometry(QtCore.QRect(-50, 1300, 1651, 1051))
        self.HPlshadow3.setStyleSheet("background: transparent;\n"
"")
        self.HPlshadow3.setText("")
        self.HPlshadow3.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\HPlshadow3.png"))
        self.HPlshadow3.setScaledContents(True)
        self.HPlshadow3.setObjectName("HPlshadow3")
        self.AUshape = QtWidgets.QFrame(Dialog)
        self.AUshape.setGeometry(QtCore.QRect(40, 2350, 1351, 6))
        self.AUshape.setStyleSheet("\n"
"background-color: #DC6158;")
        self.AUshape.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape.setObjectName("AUshape")
        self.AUshape1 = QtWidgets.QFrame(Dialog)
        self.AUshape1.setGeometry(QtCore.QRect(80, 2620, 315, 437))
        self.AUshape1.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape1.setObjectName("AUshape1")
        self.IMG1 = QtWidgets.QLabel(self.AUshape1)
        self.IMG1.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG1.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG1.setText("")
        self.IMG1.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG1.png"))
        self.IMG1.setScaledContents(True)
        self.IMG1.setObjectName("IMG1")
        self.AUname1 = QtWidgets.QLabel(self.AUshape1)
        self.AUname1.setGeometry(QtCore.QRect(30, 290, 341, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname1.setFont(font)
        self.AUname1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname1.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname1.setScaledContents(False)
        self.AUname1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname1.setWordWrap(True)
        self.AUname1.setObjectName("AUname1")
        self.HPtext_32 = QtWidgets.QLabel(self.AUshape1)
        self.HPtext_32.setGeometry(QtCore.QRect(20, 330, 321, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.HPtext_32.setFont(font)
        self.HPtext_32.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.HPtext_32.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.HPtext_32.setText("")
        self.HPtext_32.setScaledContents(False)
        self.HPtext_32.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.HPtext_32.setWordWrap(True)
        self.HPtext_32.setObjectName("HPtext_32")
        self.AUinfo1 = QtWidgets.QLabel(self.AUshape1)
        self.AUinfo1.setGeometry(QtCore.QRect(30, 330, 301, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.AUinfo1.setFont(font)
        self.AUinfo1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo1.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo1.setScaledContents(False)
        self.AUinfo1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo1.setWordWrap(True)
        self.AUinfo1.setObjectName("AUinfo1")
        self.AUshape2 = QtWidgets.QFrame(Dialog)
        self.AUshape2.setGeometry(QtCore.QRect(410, 2620, 315, 437))
        self.AUshape2.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape2.setObjectName("AUshape2")
        self.IMG2 = QtWidgets.QLabel(self.AUshape2)
        self.IMG2.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG2.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG2.setText("")
        self.IMG2.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG2.png"))
        self.IMG2.setScaledContents(True)
        self.IMG2.setObjectName("IMG2")
        self.AUname2 = QtWidgets.QLabel(self.AUshape2)
        self.AUname2.setGeometry(QtCore.QRect(40, 290, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname2.setFont(font)
        self.AUname2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname2.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname2.setScaledContents(False)
        self.AUname2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname2.setWordWrap(True)
        self.AUname2.setObjectName("AUname2")
        self.AUinfo2 = QtWidgets.QLabel(self.AUshape2)
        self.AUinfo2.setGeometry(QtCore.QRect(30, 330, 321, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo2.setFont(font)
        self.AUinfo2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo2.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo2.setScaledContents(False)
        self.AUinfo2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo2.setWordWrap(True)
        self.AUinfo2.setObjectName("AUinfo2")
        self.AUshape3 = QtWidgets.QFrame(Dialog)
        self.AUshape3.setGeometry(QtCore.QRect(740, 2620, 315, 437))
        self.AUshape3.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape3.setObjectName("AUshape3")
        self.IMG3 = QtWidgets.QLabel(self.AUshape3)
        self.IMG3.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG3.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG3.setText("")
        self.IMG3.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG3.png"))
        self.IMG3.setScaledContents(True)
        self.IMG3.setObjectName("IMG3")
        self.AUname3 = QtWidgets.QLabel(self.AUshape3)
        self.AUname3.setGeometry(QtCore.QRect(20, 290, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname3.setFont(font)
        self.AUname3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname3.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname3.setScaledContents(False)
        self.AUname3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname3.setWordWrap(True)
        self.AUname3.setObjectName("AUname3")
        self.AUinfo3 = QtWidgets.QLabel(self.AUshape3)
        self.AUinfo3.setGeometry(QtCore.QRect(20, 330, 291, 81))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo3.setFont(font)
        self.AUinfo3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo3.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo3.setScaledContents(False)
        self.AUinfo3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo3.setWordWrap(True)
        self.AUinfo3.setObjectName("AUinfo3")
        self.AUshape4 = QtWidgets.QFrame(Dialog)
        self.AUshape4.setGeometry(QtCore.QRect(1070, 2620, 315, 437))
        self.AUshape4.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape4.setObjectName("AUshape4")
        self.IMG4 = QtWidgets.QLabel(self.AUshape4)
        self.IMG4.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG4.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG4.setText("")
        self.IMG4.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG4.png"))
        self.IMG4.setScaledContents(True)
        self.IMG4.setObjectName("IMG4")
        self.AUname4 = QtWidgets.QLabel(self.AUshape4)
        self.AUname4.setGeometry(QtCore.QRect(70, 290, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname4.setFont(font)
        self.AUname4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname4.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname4.setScaledContents(False)
        self.AUname4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname4.setWordWrap(True)
        self.AUname4.setObjectName("AUname4")
        self.AUinfo4 = QtWidgets.QLabel(self.AUshape4)
        self.AUinfo4.setGeometry(QtCore.QRect(40, 330, 271, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo4.setFont(font)
        self.AUinfo4.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo4.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo4.setScaledContents(False)
        self.AUinfo4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo4.setWordWrap(True)
        self.AUinfo4.setObjectName("AUinfo4")
        self.AUshape5 = QtWidgets.QFrame(Dialog)
        self.AUshape5.setGeometry(QtCore.QRect(80, 3080, 315, 437))
        self.AUshape5.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape5.setObjectName("AUshape5")
        self.IMG5 = QtWidgets.QLabel(self.AUshape5)
        self.IMG5.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG5.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG5.setText("")
        self.IMG5.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG5.png"))
        self.IMG5.setScaledContents(True)
        self.IMG5.setObjectName("IMG5")
        self.AUname5 = QtWidgets.QLabel(self.AUshape5)
        self.AUname5.setGeometry(QtCore.QRect(50, 290, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname5.setFont(font)
        self.AUname5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname5.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname5.setScaledContents(False)
        self.AUname5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname5.setWordWrap(True)
        self.AUname5.setObjectName("AUname5")
        self.AUinfo5 = QtWidgets.QLabel(self.AUshape5)
        self.AUinfo5.setGeometry(QtCore.QRect(30, 300, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo5.setFont(font)
        self.AUinfo5.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo5.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo5.setScaledContents(False)
        self.AUinfo5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo5.setWordWrap(True)
        self.AUinfo5.setObjectName("AUinfo5")
        self.AUshape6 = QtWidgets.QFrame(Dialog)
        self.AUshape6.setGeometry(QtCore.QRect(410, 3080, 315, 437))
        self.AUshape6.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape6.setObjectName("AUshape6")
        self.IMG6 = QtWidgets.QLabel(self.AUshape6)
        self.IMG6.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG6.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG6.setText("")
        self.IMG6.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG6.png"))
        self.IMG6.setScaledContents(True)
        self.IMG6.setObjectName("IMG6")
        self.AUname6 = QtWidgets.QLabel(self.AUshape6)
        self.AUname6.setGeometry(QtCore.QRect(30, 290, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname6.setFont(font)
        self.AUname6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname6.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname6.setScaledContents(False)
        self.AUname6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname6.setWordWrap(True)
        self.AUname6.setObjectName("AUname6")
        self.AUinfo6 = QtWidgets.QLabel(self.AUshape6)
        self.AUinfo6.setGeometry(QtCore.QRect(20, 330, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo6.setFont(font)
        self.AUinfo6.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo6.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo6.setScaledContents(False)
        self.AUinfo6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo6.setWordWrap(True)
        self.AUinfo6.setObjectName("AUinfo6")
        self.AUshape7 = QtWidgets.QFrame(Dialog)
        self.AUshape7.setGeometry(QtCore.QRect(740, 3080, 315, 437))
        self.AUshape7.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape7.setObjectName("AUshape7")
        self.IMG7 = QtWidgets.QLabel(self.AUshape7)
        self.IMG7.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG7.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG7.setText("")
        self.IMG7.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG7.png"))
        self.IMG7.setScaledContents(True)
        self.IMG7.setObjectName("IMG7")
        self.AUname7 = QtWidgets.QLabel(self.AUshape7)
        self.AUname7.setGeometry(QtCore.QRect(40, 290, 351, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname7.setFont(font)
        self.AUname7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname7.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname7.setScaledContents(False)
        self.AUname7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname7.setWordWrap(True)
        self.AUname7.setObjectName("AUname7")
        self.AUinfo7 = QtWidgets.QLabel(self.AUshape7)
        self.AUinfo7.setGeometry(QtCore.QRect(30, 310, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo7.setFont(font)
        self.AUinfo7.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo7.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo7.setScaledContents(False)
        self.AUinfo7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo7.setWordWrap(True)
        self.AUinfo7.setObjectName("AUinfo7")
        self.AUshape8 = QtWidgets.QFrame(Dialog)
        self.AUshape8.setGeometry(QtCore.QRect(1070, 3080, 315, 437))
        self.AUshape8.setStyleSheet("\n"
"background-color: #FFBCAD;\n"
"border-radius: 5px; ")
        self.AUshape8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.AUshape8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.AUshape8.setObjectName("AUshape8")
        self.IMG8 = QtWidgets.QLabel(self.AUshape8)
        self.IMG8.setGeometry(QtCore.QRect(20, 20, 280, 262))
        self.IMG8.setStyleSheet("Border: 2px solid #FFFFFF;")
        self.IMG8.setText("")
        self.IMG8.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/IMG8.png"))
        self.IMG8.setScaledContents(True)
        self.IMG8.setObjectName("IMG8")
        self.AUname8 = QtWidgets.QLabel(self.AUshape8)
        self.AUname8.setGeometry(QtCore.QRect(40, 290, 291, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.AUname8.setFont(font)
        self.AUname8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUname8.setStyleSheet("font-size: 25px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUname8.setScaledContents(False)
        self.AUname8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUname8.setWordWrap(True)
        self.AUname8.setObjectName("AUname8")
        self.AUinfo8 = QtWidgets.QLabel(self.AUshape8)
        self.AUinfo8.setGeometry(QtCore.QRect(40, 300, 291, 111))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUinfo8.setFont(font)
        self.AUinfo8.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUinfo8.setStyleSheet("font-size: 23px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #FFFFFF;\n"
"text-align: left;")
        self.AUinfo8.setScaledContents(False)
        self.AUinfo8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUinfo8.setWordWrap(True)
        self.AUinfo8.setObjectName("AUinfo8")
        self.AUtabout = QtWidgets.QLabel(Dialog)
        self.AUtabout.setGeometry(QtCore.QRect(-180, 50, 861, 411))
        self.AUtabout.setStyleSheet("background: transparent;")
        self.AUtabout.setText("")
        self.AUtabout.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUtabout.png"))
        self.AUtabout.setScaledContents(True)
        self.AUtabout.setObjectName("AUtabout")
        self.AUt = QtWidgets.QLabel(Dialog)
        self.AUt.setGeometry(QtCore.QRect(-130, 280, 981, 569))
        self.AUt.setStyleSheet("background: transparent;")
        self.AUt.setText("")
        self.AUt.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUt.png"))
        self.AUt.setScaledContents(True)
        self.AUt.setObjectName("AUt")
        self.AUtours = QtWidgets.QLabel(Dialog)
        self.AUtours.setGeometry(QtCore.QRect(-30, 1280, 681, 281))
        self.AUtours.setStyleSheet("background: transparent;")
        self.AUtours.setText("")
        self.AUtours.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUtours.png"))
        self.AUtours.setScaledContents(True)
        self.AUtours.setObjectName("AUtours")
        self.AUtmission = QtWidgets.QLabel(Dialog)
        self.AUtmission.setGeometry(QtCore.QRect(710, 1270, 731, 301))
        self.AUtmission.setStyleSheet("background: transparent;")
        self.AUtmission.setText("")
        self.AUtmission.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUtmission.png"))
        self.AUtmission.setScaledContents(True)
        self.AUtmission.setObjectName("AUtmission")
        self.AUtmeet = QtWidgets.QLabel(Dialog)
        self.AUtmeet.setGeometry(QtCore.QRect(280, 2310, 821, 351))
        self.AUtmeet.setStyleSheet("background: transparent;")
        self.AUtmeet.setText("")
        self.AUtmeet.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUtmeet.png"))
        self.AUtmeet.setScaledContents(True)
        self.AUtmeet.setObjectName("AUtmeet")
        self.AUtext1 = QtWidgets.QLabel(Dialog)
        self.AUtext1.setGeometry(QtCore.QRect(90, 1550, 501, 611))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUtext1.setFont(font)
        self.AUtext1.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUtext1.setStyleSheet("font-size: 45px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUtext1.setScaledContents(False)
        self.AUtext1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.AUtext1.setWordWrap(True)
        self.AUtext1.setObjectName("AUtext1")
        self.AUtext2 = QtWidgets.QLabel(Dialog)
        self.AUtext2.setGeometry(QtCore.QRect(830, 1620, 541, 631))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        self.AUtext2.setFont(font)
        self.AUtext2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.AUtext2.setStyleSheet("font-size: 45px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"text-align: left;")
        self.AUtext2.setScaledContents(False)
        self.AUtext2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.AUtext2.setWordWrap(True)
        self.AUtext2.setObjectName("AUtext2")
        self.AUimage2 = QtWidgets.QLabel(Dialog)
        self.AUimage2.setGeometry(QtCore.QRect(-100, 790, 1561, 847))
        self.AUimage2.setStyleSheet("background: transparent;")
        self.AUimage2.setText("")
        self.AUimage2.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\AUimages/AUimage2.png"))
        self.AUimage2.setScaledContents(True)
        self.AUimage2.setObjectName("AUimage2")
        self.HPlshadow1 = QtWidgets.QLabel(Dialog)
        self.HPlshadow1.setGeometry(QtCore.QRect(-230, 530, 1861, 1131))
        self.HPlshadow1.setStyleSheet("background: transparent;")
        self.HPlshadow1.setText("")
        self.HPlshadow1.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\HPlshadow1.png"))
        self.HPlshadow1.setScaledContents(True)
        self.HPlshadow1.setObjectName("HPlshadow1")
        self.ctu = QtWidgets.QPushButton(Dialog)
        self.ctu.setGeometry(QtCore.QRect(650, 3810, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.ctu.setFont(font)
        self.ctu.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ctu.setStyleSheet("font:30px;\n"
"color: #7A0C0C;\n"
"background: transparent;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.ctu.setObjectName("ctu")
        self.Aus = QtWidgets.QPushButton(Dialog)
        self.Aus.setGeometry(QtCore.QRect(660, 3740, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Aus.setFont(font)
        self.Aus.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Aus.setStyleSheet("font:30px;\n"
"color: #7A0C0C;\n"
"background: transparent;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.Aus.setObjectName("Aus")
        self.trmsCon = QtWidgets.QPushButton(Dialog)
        self.trmsCon.setGeometry(QtCore.QRect(870, 3740, 241, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.trmsCon.setFont(font)
        self.trmsCon.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trmsCon.setStyleSheet("font:30px;\n"
"color: #7A0C0C;\n"
"background: transparent;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.trmsCon.setObjectName("trmsCon")
        self.priPly = QtWidgets.QPushButton(Dialog)
        self.priPly.setGeometry(QtCore.QRect(860, 3810, 231, 31))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.priPly.setFont(font)
        self.priPly.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.priPly.setStyleSheet("font:30px;\n"
"color: #7A0C0C;\n"
"background: transparent;\n"
"border-radius: 5px; \n"
"\n"
"")
        self.priPly.setObjectName("priPly")
        self.HP_footer = QtWidgets.QFrame(Dialog)
        self.HP_footer.setGeometry(QtCore.QRect(-11, 3620, 1451, 361))
        self.HP_footer.setStyleSheet(" border: 2px solid brown;\n"
"    border-radius: 5px;  \n"
"background-color: rgb(255, 236, 218);")
        self.HP_footer.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HP_footer.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HP_footer.setObjectName("HP_footer")
        self.HP_Icon = QtWidgets.QLabel(self.HP_footer)
        self.HP_Icon.setGeometry(QtCore.QRect(0, -30, 451, 301))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.HP_Icon.setFont(font)
        self.HP_Icon.setStyleSheet("background: transparent;\n"
"border: clear;")
        self.HP_Icon.setText("")
        self.HP_Icon.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../Icon.png"))
        self.HP_Icon.setScaledContents(True)
        self.HP_Icon.setObjectName("HP_Icon")
        self.LI_Icon = QtWidgets.QLabel(self.HP_footer)
        self.LI_Icon.setGeometry(QtCore.QRect(-60, -20, 541, 311))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.LI_Icon.setFont(font)
        self.LI_Icon.setStyleSheet("border: 1px solid transparent;\n"
"background: transparent;")
        self.LI_Icon.setText("")
        self.LI_Icon.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\Icon.png"))
        self.LI_Icon.setScaledContents(True)
        self.LI_Icon.setObjectName("LI_Icon")
        self.HPshape1_12 = QtWidgets.QFrame(self.HP_footer)
        self.HPshape1_12.setGeometry(QtCore.QRect(850, 30, 3, 231))
        self.HPshape1_12.setStyleSheet("\n"
"\n"
"background-color: rgba(130, 27, 26, 0.5);")
        self.HPshape1_12.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.HPshape1_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.HPshape1_12.setLineWidth(0)
        self.HPshape1_12.setObjectName("HPshape1_12")
        self.HPtext7 = QtWidgets.QLabel(self.HP_footer)
        self.HPtext7.setGeometry(QtCore.QRect(40, 210, 291, 221))
        font = QtGui.QFont()
        font.setFamily("Courier New")
        font.setPointSize(-1)
        self.HPtext7.setFont(font)
        self.HPtext7.setStyleSheet("font-size: 20px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"border: none;")
        self.HPtext7.setScaledContents(False)
        self.HPtext7.setAlignment(QtCore.Qt.AlignCenter)
        self.HPtext7.setWordWrap(True)
        self.HPtext7.setObjectName("HPtext7")
        self.HPtext5 = QtWidgets.QLabel(self.HP_footer)
        self.HPtext5.setGeometry(QtCore.QRect(640, 30, 191, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.HPtext5.setFont(font)
        self.HPtext5.setStyleSheet("font-size: 30px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"border: none")
        self.HPtext5.setScaledContents(False)
        self.HPtext5.setAlignment(QtCore.Qt.AlignCenter)
        self.HPtext5.setWordWrap(True)
        self.HPtext5.setObjectName("HPtext5")
        self.HPtext6 = QtWidgets.QLabel(self.HP_footer)
        self.HPtext6.setGeometry(QtCore.QRect(890, 35, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.HPtext6.setFont(font)
        self.HPtext6.setStyleSheet("font-size: 30px;\n"
"text-align: center;\n"
"background: transparent;\n"
"color: #7A0C0C;\n"
"border: none")
        self.HPtext6.setScaledContents(False)
        self.HPtext6.setAlignment(QtCore.Qt.AlignCenter)
        self.HPtext6.setWordWrap(True)
        self.HPtext6.setObjectName("HPtext6")
        self.HPtext5.raise_()
        self.HPtext6.raise_()
        self.HP_Icon.raise_()
        self.LI_Icon.raise_()
        self.HPshape1_12.raise_()
        self.HPtext7.raise_()
        self.HP_footer.raise_()
        self.AUimage2.raise_()
        self.HPlshadow1.raise_()
        self.HPbG.raise_()
        self.AUimage1.raise_()
        self.AUt.raise_()
        self.AU_header.raise_()
        self.HPlshadow3.raise_()
        self.AUshape.raise_()
        self.AUshape1.raise_()
        self.AUshape2.raise_()
        self.AUshape3.raise_()
        self.AUshape4.raise_()
        self.AUshape5.raise_()
        self.AUshape6.raise_()
        self.AUshape7.raise_()
        self.AUshape8.raise_()
        self.AUtabout.raise_()
        self.AUtours.raise_()
        self.AUtmission.raise_()
        self.AUtmeet.raise_()
        self.AUtext1.raise_()
        self.AUtext2.raise_()
        self.ctu.raise_()
        self.Aus.raise_()
        self.trmsCon.raise_()
        self.priPly.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.LogIn_2.setText(_translate("Dialog", "Log In"))
        self.SignUp.setText(_translate("Dialog", "Sign Up"))
        self.AUname1.setText(_translate("Dialog", "CHRISTIAN R. BATALLER"))
        self.AUinfo1.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL:christianbataller788@ gmail com  "))
        self.AUname2.setText(_translate("Dialog", "JOHN CRIS C. CACULITAN"))
        self.AUinfo2.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL:johncriscaculitan01@gmail.    com "))
        self.AUname3.setText(_translate("Dialog", "KING ANDREI B. GUTIERREZ"))
        self.AUinfo3.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL: gutierrez.kingandrei21@ gmail.com "))
        self.AUname4.setText(_translate("Dialog", "JAKIM D. LOPEZ"))
        self.AUinfo4.setText(_translate("Dialog", "ROLE:PROJECT MANAGER  EMAIL:jakimlopez28@gmail.com "))
        self.AUname5.setText(_translate("Dialog", "ZYRA JOY O. NIONES"))
        self.AUinfo5.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL: aryzsenion@gmail.com"))
        self.AUname6.setText(_translate("Dialog", "ANNIE ROSE S. RAQUEM"))
        self.AUinfo6.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL:raquemannierose36@gmail. com "))
        self.AUname7.setText(_translate("Dialog", "MA. ROSE L. TOLENTINO"))
        self.AUinfo7.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL:ma.roselacetolentino@ gmail.com"))
        self.AUname8.setText(_translate("Dialog", "KALELLE B. VICTORIO"))
        self.AUinfo8.setText(_translate("Dialog", "ROLE: SOFTWARE DEVELOPER  EMAIL: kalelleee@gmail.com"))
        self.AUtext1.setText(_translate("Dialog", "Penpal was born from a simple idea: to make it easy for people to find and connect with new friends who share their interests and passions. We believe that meaningful connections can enrich lives, and we set out to create an app that would help people build genuine friendships effortlessly."))
        self.AUtext2.setText(_translate("Dialog", "Our mission is to provide a platform where users can discover and connect with like-minded individuals. We strive to foster a community where friendships are made based on shared interests, values, and experiences. With Penpal, we aim to make the process of finding new friends enjoyable and rewarding, ultimately creating a world where everyone can find their perfect match."))
        self.ctu.setText(_translate("Dialog", "CONTACT US"))
        self.Aus.setText(_translate("Dialog", "ABOUT US"))
        self.trmsCon.setText(_translate("Dialog", "TERMS AND CONDITION"))
        self.priPly.setText(_translate("Dialog", "PRIVACY AND POLICY"))
        self.HPtext7.setText(_translate("Dialog", "All rights reserved.2025. PenPal"))
        self.HPtext5.setText(_translate("Dialog", "INFORMATION"))
        self.HPtext6.setText(_translate("Dialog", "LEGAL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
