# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\chris\OneDrive\Desktop\For Python Code\penpal\Forgot Pass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1440, 780)
        Dialog.setMinimumSize(QtCore.QSize(581, 96))
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.LI_Header = QtWidgets.QFrame(Dialog)
        self.LI_Header.setGeometry(QtCore.QRect(0, 0, 1440, 105))
        self.LI_Header.setStyleSheet("background: qlineargradient(\n"
"    spread:pad, \n"
"    x1:0, y1:0, x2:1, y2:0, \n"
"    stop:0 #EDC27E, \n"
"    stop:0.526 #EDC27E, \n"
"    stop:1 #DC586D\n"
");\n"
"\n"
"")
        self.LI_Header.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.LI_Header.setFrameShadow(QtWidgets.QFrame.Raised)
        self.LI_Header.setObjectName("LI_Header")
        self.LI_HeaderIcon = QtWidgets.QLabel(self.LI_Header)
        self.LI_HeaderIcon.setGeometry(QtCore.QRect(-70, -20, 274, 146))
        font = QtGui.QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(28)
        self.LI_HeaderIcon.setFont(font)
        self.LI_HeaderIcon.setStyleSheet("color: rgb(98, 65, 66);\n"
"background: transparent;")
        self.LI_HeaderIcon.setText("")
        self.LI_HeaderIcon.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../../../Downloads/HeaderIcon.png"))
        self.LI_HeaderIcon.setScaledContents(True)
        self.LI_HeaderIcon.setObjectName("LI_HeaderIcon")
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(261, 149, 901, 602))
        self.frame.setMinimumSize(QtCore.QSize(901, 602))
        self.frame.setStyleSheet("background-color: rgb(255, 240, 216);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(40, 240, 351, 71))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(5)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(351, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(-1)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(122, 12, 12); font-size: 23px;")
        self.label_2.setObjectName("label_2")
        
        # Added: Email input field
        self.email_input = QtWidgets.QLineEdit(self.frame)
        self.email_input.setGeometry(QtCore.QRect(100, 290, 323, 36))
        self.email_input.setStyleSheet("border: 2px solid #E58D76; padding: 5px;")
        self.email_input.setPlaceholderText("Enter your email")
        self.email_input.setObjectName("email_input")
        
        # Submit button
        self.submit_button = QtWidgets.QPushButton(self.frame)
        self.submit_button.setGeometry(QtCore.QRect(300, 410, 119, 36))
        self.submit_button.setStyleSheet("background-color: #DC6158; color: white; border-radius: 5px;")
        self.submit_button.setText("Submit")
        self.submit_button.setObjectName("submit_button")

        # Connect Submit button to the function
        self.submit_button.clicked.connect(self.handle_submit)  # Ensures button is functional

        
        self.ForgotPassTEXT = QtWidgets.QLabel(self.frame)
        self.ForgotPassTEXT.setGeometry(QtCore.QRect(90, 190, 488, 41))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.ForgotPassTEXT.sizePolicy().hasHeightForWidth())
        self.ForgotPassTEXT.setSizePolicy(sizePolicy)
        self.ForgotPassTEXT.setMinimumSize(QtCore.QSize(488, 36))
        font = QtGui.QFont()
        font.setFamily("Rockwell Condensed")
        font.setPointSize(36)
        font.setBold(False)
        self.ForgotPassTEXT.setFont(font)
        self.ForgotPassTEXT.setStyleSheet("color: rgb(220, 97, 88); font-size: 40px; font-weight: bold;")
        self.ForgotPassTEXT.setObjectName("ForgotPassTEXT")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(-30, 0, 1031, 601))
        self.label_4.setStyleSheet("background: transparent;")
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../PenpalFE/FPshadow.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.FPimage1 = QtWidgets.QLabel(self.frame)
        self.FPimage1.setGeometry(QtCore.QRect(140, 0, 1131, 602))
        self.FPimage1.setMinimumSize(QtCore.QSize(421, 602))
        self.FPimage1.setStyleSheet("background: transparent;")
        self.FPimage1.setText("")
        self.FPimage1.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../PenpalFE/FPimage1.png"))
        self.FPimage1.setScaledContents(True)
        self.FPimage1.setObjectName("FPimage1")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(-50, 0, 245, 127))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:\\Users\\chris\\OneDrive\\Desktop\\For Python Code\\penpal\\../../PenpalFE/FPlogo.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "EMAIL:"))
        self.ForgotPassTEXT.setText(_translate("Dialog", "FORGOT PASSWORD"))

    # Added: Function to handle submit button click
    def handle_submit(self):
        email = self.email_input.text()
        if email:
            print(f"Proceeding with email: {email}")
            # Logic to navigate to the next page goes here
        else:
            QtWidgets.QMessageBox.warning(None, "Input Error", "Please enter an email address.")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
