# Form implementation generated from reading ui file 'c:\Users\chris\OneDrive\Desktop\For Python Code\penpal\TERMS&CON.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(931, 686)
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(0, 0, 931, 71))
        self.widget.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(237, 194, 126, 255), stop:1 rgba(220, 88, 109, 255));\n"
"")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(parent=self.widget)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 120, 51))
        self.widget_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 247, 245, 255), stop:1 rgba(255, 247, 245, 0));\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.widget_3 = QtWidgets.QWidget(parent=self.widget)
        self.widget_3.setGeometry(QtCore.QRect(800, 20, 81, 41))
        self.widget_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(240, 240, 240, 255));\n"
"")
        self.widget_3.setObjectName("widget_3")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget)
        self.widget_4.setGeometry(QtCore.QRect(710, 20, 81, 41))
        self.widget_4.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(240, 240, 240, 255));\n"
"\n"
"")
        self.widget_4.setObjectName("widget_4")
        self.widget_5 = QtWidgets.QWidget(parent=Dialog)
        self.widget_5.setGeometry(QtCore.QRect(0, 70, 931, 621))
        self.widget_5.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(240, 240, 240, 255));\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.widget_6 = QtWidgets.QWidget(parent=self.widget_5)
        self.widget_6.setGeometry(QtCore.QRect(70, 20, 781, 581))
        self.widget_6.setStyleSheet("background-color: rgba(255, 240, 216, 255);\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.line = QtWidgets.QFrame(parent=self.widget_6)
        self.line.setGeometry(QtCore.QRect(170, 40, 530, 3))
        self.line.setMinimumSize(QtCore.QSize(530, 0))
        self.line.setStyleSheet("background-color: rgba(221, 91, 110, 255);\n"
"")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.widget_6)
        self.line_2.setGeometry(QtCore.QRect(170, 530, 530, 3))
        self.line_2.setMinimumSize(QtCore.QSize(530, 0))
        self.line_2.setStyleSheet("background-color: rgba(221, 91, 110, 255);\n"
"")
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(parent=self.widget_6)
        self.line_3.setGeometry(QtCore.QRect(170, 40, 3, 491))
        self.line_3.setMinimumSize(QtCore.QSize(0, 491))
        self.line_3.setStyleSheet("background-color: rgba(221, 91, 110, 255);\n"
"")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(parent=self.widget_6)
        self.line_4.setGeometry(QtCore.QRect(700, 40, 3, 491))
        self.line_4.setMinimumSize(QtCore.QSize(0, 491))
        self.line_4.setStyleSheet("background-color: rgba(221, 91, 110, 255);\n"
"")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.widget_7 = QtWidgets.QWidget(parent=self.widget_6)
        self.widget_7.setGeometry(QtCore.QRect(170, 40, 531, 61))
        self.widget_7.setStyleSheet("background-color: rgba(255, 159, 137, 255);\n"
"")
        self.widget_7.setObjectName("widget_7")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
